name: Testing stuff

on:
  push:
    branches:
      - testing

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commitsss
        env:
          COMMITTSS: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMITTSS"
      - name: easnv
        run: echo "$github.event"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ',') }}
        run: echo "$COMMIT_MESSAGES"
      - name: check for skip
        if: contains(join(github.event.commits.*.message, ','), '#SKIP')
        run: echo "Skipping due to commit message containing #SKIP"
